### PR TITLE
Add RHEL System Roles section

### PR DESCRIPTION
**Pull request by jwennerberg**
Initial RHEL System Roles section added to the Ansible assignment. Will update with more advanced use-case.

Let me know if it should be a separate assignment instead.

### CODE REVIEW

**Comment by hger** [comment]
I think it looks great,also good that you correct previous parts. i would however make it into a separate assignement as the existing one is already quite long. Also makes room for some more actions to be added in very short manner like:

"Also try to do X by evaluating what roles are installed. Here is an example XYZ"

Or something similar?

**Comment by jwennerberg** [comment]
Yeah I agree. The complete lab will be quite long.

The problem is that most of the prereqs are the same and would have to be copied if it's to become a separate assignment.

Maybe I can convert it to be a bit more modular.
4. Ansible overview and prereqs
4a. Linux automation with Ansible
4b. Windows automation with Ansible
4c. RHEL System Roles

So students can choose any combination of a, b and c. 

What do you think?

**Comment by hger** [comment]
Yes that would also be a good option, perhaps even put the order like so:
Ansible overview and prereqs
Linux automation with Ansible
RHEL System Roles
Windows automation with Ansible

So there is some linux then more linux then some windows. Also the system roles are a real great time-saver for the sysadmin

**Comment by jwennerberg** [comment]
As per Håkans excellent advice I'm merging this myself :)

**Pull request merged**
